from decimal import Decimal
from django.db import transaction
from django.db.models import Sum
from django.utils import timezone
from datetime import timedelta
from .models import Account, AccountingPeriod, JournalEntry, JournalLine

DEFAULT_ACCOUNTS=[
('1000','Cash','asset'),('1010','Bank','asset'),('1020','Mobile Money','asset'),('1100','Accounts Receivable','asset'),('1200','Inventory','asset'),('1300','Prepaid Expenses','asset'),
('2000','Accounts Payable','liability'),('2100','Taxes Payable','liability'),('3000','Owner / Shareholders Equity','equity'),('3100','Retained Earnings','equity'),
('4000','Room Revenue','revenue'),('4100','Restaurant Revenue','revenue'),('4200','Service Revenue','revenue'),('4900','Sales Discounts','revenue'),
('5000','Cost of Goods Sold','cogs'),('6000','Operating Expenses','expense'),('6100','Payroll Expense','expense'),('6200','Utilities Expense','expense'),('6300','Rent Expense','expense'),('6400','Maintenance Expense','expense'),('6500','Other Expenses','expense'),
]

def seed_accounts():
    for code,name,typ in DEFAULT_ACCOUNTS: Account.objects.get_or_create(code=code,defaults={'name':name,'account_type':typ})

def account(code): return Account.objects.get(code=code)

def period_for(date):
    p=AccountingPeriod.objects.filter(start_date__lte=date,end_date__gte=date,status=AccountingPeriod.OPEN).first()
    if p: return p
    return AccountingPeriod.objects.create(name=f'{date:%B %Y}',start_date=date.replace(day=1),end_date=_month_end(date))

def _month_end(d):
    import calendar
    return d.replace(day=calendar.monthrange(d.year,d.month)[1])

def _replace(source_type,source_id,date,description,lines,user=None,reference=''):
    old=JournalEntry.objects.filter(source_type=source_type,source_id=source_id).first()
    if old: old.delete()
    with transaction.atomic():
        e=JournalEntry.objects.create(date=date,period=period_for(date),description=description,reference=reference,source_type=source_type,source_id=source_id,posted_by=user)
        for code,debit,credit,desc in lines:
            if Decimal(str(debit or 0)) or Decimal(str(credit or 0)):
                JournalLine.objects.create(entry=e,account=account(code),debit=debit or 0,credit=credit or 0,description=desc)
        return e

def post_expense(expense,user=None):
    cash={'cash':'1000','bank':'1010','mobile':'1020','card':'1010'}.get(expense.payment_method,'1000')
    expense_code={'payroll':'6100','salary':'6100','utilities':'6200','rent':'6300','maintenance':'6400'}.get(expense.category.name.lower(),'6500')
    return _replace('expense',expense.pk,expense.date,expense.description,[(expense_code,expense.amount,0,expense.description),(cash,0,expense.amount,expense.payment_method)],user,expense.reference)

def _revenue_entry(source_type, source_id, date, account_code, amount, description, user=None, reference=''):
    return _replace(source_type, source_id, date, description, [('1100', amount, 0, 'Accounts receivable'), (account_code, 0, amount, description)], user, reference)

def post_invoice(invoice,user=None):
    """Post invoice revenue on the dates the revenue was earned.

    Room revenue follows RoomStay nights (start inclusive, end exclusive),
    restaurant revenue follows Order.created_at, and services follow Service.date.
    This prevents the invoice creation date from moving several days of revenue
    into the wrong accounting period.
    """
    from hotel.models import Service
    from restaurant.models import Order
    from django.db.models import Sum

    # Remove the old aggregate invoice journal and previously generated
    # revenue-detail journals for this invoice's components.
    JournalEntry.objects.filter(source_type='invoice', source_id=invoice.pk).delete()
    booking = invoice.booking
    stay_ids = list(booking.room_stays.values_list('id', flat=True))
    order_ids = list(Order.objects.filter(booking=booking).values_list('id', flat=True))
    service_ids = list(Service.objects.filter(booking=booking).values_list('id', flat=True))
    # Remove both legacy room journals (one per stay) and the newer
    # date-level room-night journals generated by earlier syncs.
    JournalEntry.objects.filter(source_type='invoice_room', source_id__in=stay_ids).delete()
    for stay_id in stay_ids:
        JournalEntry.objects.filter(
            source_type='invoice_room_night',
            reference__startswith=f'INV-{invoice.pk}/ROOM-{stay_id}/'
        ).delete()
    JournalEntry.objects.filter(source_type='invoice_restaurant', source_id__in=order_ids).delete()
    JournalEntry.objects.filter(source_type='invoice_service', source_id__in=service_ids).delete()
    JournalEntry.objects.filter(source_type='invoice_discount', source_id=invoice.pk).delete()

    entries=[]
    # RoomStay uses an exclusive end date, matching the existing Finance P&L.
    today = timezone.localdate()
    for stay in booking.room_stays.all().order_by('start_date','id'):
        # Closed stays use the existing start-inclusive/end-exclusive rule.
        # An open stay, however, earns the current hotel night immediately;
        # otherwise a booking/check-in made today would post no revenue until
        # tomorrow. This mirrors billing.services.get_booking_totals().
        end = stay.end_date
        current = stay.start_date
        if end:
            # Closed stay: start inclusive, end exclusive.
            last_date = end - timedelta(days=1)
        else:
            # Open stay: an established stay earns nights through yesterday.
            # A stay that starts today must still carry one billable night
            # immediately. This mirrors billing.services.get_booking_totals().
            last_date = today if stay.start_date == today else today - timedelta(days=1)
        while current <= last_date:
            if stay.rate:
                # A multi-night stay must produce one accounting entry per
                # earned night.  The source ID must therefore be unique per
                # stay/date; using stay.pk for every night caused _replace()
                # to delete the previous night and leave only the last one.
                # The P&L then correctly sums these daily entries to:
                #     nights * nightly_rate
                night_source_id = (int(stay.pk) * 1_000_000) + current.toordinal()
                entries.append(
                    _revenue_entry(
                        'invoice_room_night',
                        night_source_id,
                        current,
                        '4000',
                        stay.rate,
                        f'Room revenue - Room {stay.room.number} - {current}',
                        user,
                        f'INV-{invoice.pk}/ROOM-{stay.pk}/{current}'
                    )
                )
            current += timedelta(days=1)

    for order in Order.objects.filter(booking=booking).only('id','created_at','total_amount'):
        if order.total_amount:
            d = timezone.localtime(order.created_at).date() if order.created_at else booking.check_out or today
            entries.append(_revenue_entry('invoice_restaurant', order.pk, d, '4100', order.total_amount, f'Restaurant order #{order.pk}', user, f'INV-{invoice.pk}/ORDER-{order.pk}'))

    for service in Service.objects.filter(booking=booking).only('id','date','total_amount'):
        if service.total_amount:
            entries.append(_revenue_entry('invoice_service', service.pk, service.date, '4200', service.total_amount, f'Service #{service.pk}', user, f'INV-{invoice.pk}/SERVICE-{service.pk}'))

    if invoice.discount:
        # Discount is recognized with the invoice settlement date because it is
        # an invoice-level adjustment rather than a separately dated service.
        discount_date = invoice.booking.check_out or (invoice.created.date() if invoice.created else today)
        entries.append(_replace('invoice_discount', invoice.pk, discount_date, f'Invoice #{invoice.pk} discount', [('4900', invoice.discount, 0, 'Sales discount'), ('1100', 0, invoice.discount, 'Accounts receivable')], user, f'INV-{invoice.pk}/DISCOUNT'))
    return entries

def post_payment(payment,user=None):
    cash={'cash':'1000','bank':'1010','mobile':'1020','card':'1010'}.get(str(payment.payment_method).lower(),'1000')
    return _replace('payment',payment.pk,payment.created.date(),f'Customer payment #{payment.pk}',[(cash,payment.amount,0,'Customer collection'),('1100',0,payment.amount,'Accounts receivable')],user)

def post_purchase(purchase,user=None):
    amount=purchase.total_amount or 0
    return _replace('purchase',purchase.pk,purchase.date,f'Purchase #{purchase.pk}',[('1200',amount,0,'Inventory purchase'),('2000',0,amount,'Supplier payable')],user)

def post_supplier_payment(payment,user=None):
    cash={'cash':'1000','bank':'1010','mobile':'1020','card':'1010'}.get(payment.payment_method,'1000')
    return _replace('supplier_payment',payment.pk,payment.date,f'Supplier payment #{payment.pk}',[('2000',payment.amount,0,'Accounts payable'),(cash,0,payment.amount,'Supplier payment')],user)

def post_inventory_movement(m,user=None):
    cost=m.quantity*m.unit_cost
    if m.movement_type=='receipt': lines=[('1200',cost,0,'Inventory receipt'),('2000',0,cost,'Inventory payable')]
    elif m.movement_type=='issue': lines=[('5000',cost,0,'COGS'),('1200',0,cost,'Inventory issue')]
    else: lines=[('5000',cost,0,'Inventory adjustment') ,('1200',0,cost,'Inventory adjustment')]
    return _replace('inventory_movement',m.pk,m.date,f'Inventory {m.movement_type} #{m.pk}',lines,user,m.reference)

def sync_operational_journals(user=None):
    from billing.models import Invoice,Payment
    from finance.models import Expense
    from purchases.models import Purchase
    seed_accounts()
    counts={}
    for qs,fn,key in [(Invoice.objects.all(),post_invoice,'invoices'),(Payment.objects.all(),post_payment,'payments'),(Expense.objects.all(),post_expense,'expenses'),(Purchase.objects.all(),post_purchase,'purchases')]:
        n=0
        for obj in qs.select_related(): fn(obj,user); n+=1
        counts[key]=n
    return counts


def get_operational_receivables_as_of(end_date):
    """Return the HMS customer receivable balance as of a date.

    This is the authoritative operational AR calculation used by Finance and
    the Balance Sheet. It includes all invoices created on/before the date,
    values earned through that date, and only payments received on/before the
    date. This prevents the ledger statement and customer receivables report
    from using different cut-off rules.
    """
    from billing.models import Invoice
    from billing.services import get_booking_totals
    from datetime import date, datetime

    if isinstance(end_date, datetime):
        end_date = end_date.date()
    elif isinstance(end_date, str):
        try:
            end_date = date.fromisoformat(end_date)
        except ValueError:
            end_date = date.today()

    total = Decimal('0.00')
    invoices = Invoice.objects.filter(created__date__lte=end_date).prefetch_related('payment_set')
    for invoice in invoices:
        totals = get_booking_totals(invoice.booking, as_of=end_date, include_checkout_night=False)
        amount = max(
            Decimal('0.00'),
            totals['room_total'] + totals['restaurant_total'] +
            totals['service_total'] - (invoice.discount or Decimal('0.00')),
        )
        paid = sum(
            (payment.amount for payment in invoice.payment_set.all()
             if payment.created and payment.created.date() <= end_date),
            Decimal('0.00'),
        )
        total += max(Decimal('0.00'), amount - paid)
    return total


def get_profit_loss_statement(start, end):
    """Return the authoritative period P&L used by both Finance and Accounting.

    Revenue, COGS and operating expenses are read from posted journal lines.
    Purchases are used as a management-basis COGS fallback only when there are
    no posted COGS entries in the period, preserving the existing HMS policy.
    """
    from purchases.models import Purchase

    qs = JournalLine.objects.filter(
        entry__date__gte=start,
        entry__date__lte=end,
        entry__is_posted=True,
        account__account_type__in=['revenue', 'cogs', 'expense'],
    ).values('account__code', 'account__name', 'account__account_type').annotate(
        debit=Sum('debit'), credit=Sum('credit')
    ).order_by('account__code')

    rows = []
    for r in qs:
        typ = r['account__account_type']
        balance = ((r['credit'] or 0) - (r['debit'] or 0)) if typ == 'revenue' else ((r['debit'] or 0) - (r['credit'] or 0))
        r['balance'] = balance
        rows.append(r)

    revenue_accounts = {
        '4000': 'Room Revenue',
        '4100': 'Restaurant Revenue',
        '4200': 'Service Revenue',
        '4900': 'Sales Discounts',
    }
    revenue = {code: Decimal('0.00') for code in revenue_accounts}
    for r in rows:
        if r['account__account_type'] == 'revenue' and r['account__code'] in revenue:
            revenue[r['account__code']] += Decimal(str(r['balance'] or 0))

    posted_cogs = sum((Decimal(str(r['balance'] or 0)) for r in rows if r['account__account_type'] == 'cogs'), Decimal('0.00'))
    purchase_cogs = Purchase.objects.filter(date__gte=start, date__lte=end).aggregate(total=Sum('total_amount'))['total'] or Decimal('0.00')
    if posted_cogs:
        cogs = posted_cogs
        cogs_source = 'Posted inventory consumption (COGS)'
    else:
        cogs = purchase_cogs
        cogs_source = 'Purchases / COGS (management basis)'

    expense_rows = [r for r in rows if r['account__account_type'] == 'expense']
    expenses = sum((Decimal(str(r['balance'] or 0)) for r in expense_rows), Decimal('0.00'))
    total_revenue = sum(revenue.values(), Decimal('0.00'))
    gross_profit = total_revenue - cogs
    operating_profit = gross_profit - expenses

    return {
        'revenue': revenue,
        'total_revenue': total_revenue,
        'posted_cogs': posted_cogs,
        'purchase_cogs': purchase_cogs,
        'cogs': cogs,
        'cogs_source': cogs_source,
        'expense_rows': expense_rows,
        'total_expenses': expenses,
        'gross_profit': gross_profit,
        'operating_profit': operating_profit,
        'net_other_income': Decimal('0.00'),
        'net_profit': operating_profit,
    }
