# Generated by Django 6.1.1 on 2026-09-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_ledger_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.room'),
        ),
    ]
