
def seed_accounts(apps, schema_editor):
    Account=apps.get_model('accounting','Account')
    defaults=[('1000','Cash','asset'),('1010','Bank','asset'),('1020','Mobile Money','asset'),('1100','Accounts Receivable','asset'),('1200','Inventory','asset'),('1300','Prepaid Expenses','asset'),('2000','Accounts Payable','liability'),('2100','Taxes Payable','liability'),('3000','Owner / Shareholders Equity','equity'),('3100','Retained Earnings','equity'),('4000','Room Revenue','revenue'),('4100','Restaurant Revenue','revenue'),('4200','Service Revenue','revenue'),('4900','Sales Discounts','revenue'),('5000','Cost of Goods Sold','cogs'),('6000','Operating Expenses','expense'),('6100','Payroll Expense','expense'),('6200','Utilities Expense','expense'),('6300','Rent Expense','expense'),('6400','Maintenance Expense','expense'),('6500','Other Expenses','expense')]
    for code,name,typ in defaults: Account.objects.get_or_create(code=code,defaults={'name':name,'account_type':typ})

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal

class Migration(migrations.Migration):
    initial=True
    dependencies=[('auth','0012_alter_user_first_name_max_length'),('purchases','0001_initial')]
    operations=[
        migrations.CreateModel(name='Account',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=20,unique=True)),('name',models.CharField(max_length=150)),('account_type',models.CharField(choices=[('asset','Asset'),('liability','Liability'),('equity','Equity'),('revenue','Revenue'),('cogs','Cost of Goods Sold'),('expense','Expense')],max_length=20)),('active',models.BooleanField(default=True)),('opening_balance',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('parent',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='children',to='accounting.account'))],options={'ordering':['code'] }),
        migrations.CreateModel(name='AccountingPeriod',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100,unique=True)),('start_date',models.DateField()),('end_date',models.DateField()),('status',models.CharField(choices=[('open','Open'),('closed','Closed')],default='open',max_length=10)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user'))],options={'ordering':['-start_date']}),
        migrations.CreateModel(name='InventoryMovement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('date',models.DateField(default=django.utils.timezone.localdate)),('movement_type',models.CharField(choices=[('receipt','Receipt'),('issue','Issue / COGS'),('adjustment','Adjustment')],max_length=20)),('quantity',models.DecimalField(decimal_places=2,max_digits=14)),('unit_cost',models.DecimalField(decimal_places=2,max_digits=14)),('reference',models.CharField(blank=True,max_length=100)),('notes',models.TextField(blank=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user')),('item',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='accounting_movements',to='purchases.inventoryitem'))]),
        migrations.CreateModel(name='SupplierPayment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('date',models.DateField(default=django.utils.timezone.localdate)),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('payment_method',models.CharField(choices=[('cash','Cash'),('bank','Bank'),('card','Card'),('mobile','Mobile Money'),('other','Other')],default='cash',max_length=20)),('reference',models.CharField(blank=True,max_length=100)),('notes',models.TextField(blank=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user')),('created',models.DateTimeField(auto_now_add=True)),('supplier',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='accounting_payments',to='purchases.supplier'))]),
        migrations.CreateModel(name='JournalEntry',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('date',models.DateField(default=django.utils.timezone.localdate)),('reference',models.CharField(blank=True,max_length=100)),('description',models.CharField(max_length=255)),('source_type',models.CharField(blank=True,max_length=50)),('source_id',models.PositiveBigIntegerField(blank=True,null=True)),('posted_at',models.DateTimeField(auto_now_add=True)),('is_posted',models.BooleanField(default=True)),('period',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='journal_entries',to='accounting.accountingperiod')),('posted_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user')),],options={'ordering':['-date','-id']}),
        migrations.CreateModel(name='JournalLine',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('debit',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('credit',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('description',models.CharField(blank=True,max_length=255)),('account',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='journal_lines',to='accounting.account')),('entry',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='lines',to='accounting.journalentry'))],options={'ordering':['id']}),
        migrations.AddConstraint(model_name='journalentry',constraint=models.UniqueConstraint(fields=('source_type','source_id'),name='uniq_accounting_source')),

        migrations.RunPython(seed_accounts, migrations.RunPython.noop),
    ]
